### ISSUE TITLE
I get nothing from Maixduino

### ISSUE THREAD

**Issue by nogleo** [Josverl/micropython-stubber#15]
Anyone ever tried on Sipeed Maixduino? I followed the instructions and when I run the createstubs I get nothing.

**Comment by Josverl** [comment]
hi , do you mean this [Maxduino maixpy port](https://maixpy.sipeed.com/en/) ?

can you be a bit more specific about hwat you did , and what the result of that was , or was not  in your case.

**Comment by Josverl** [comment]
closing stale item.
