### ISSUE TITLE
Question about non-VS Code support and board support

### ISSUE THREAD

**Issue by vincentchov** [Josverl/micropython-stubber#212]
Sorry if this the wrong place to ask questions, but is the Micropy CLI compatible with other text editors like NeoVim? Also, are the stubs compatible with the ESP8266? Thanks!

**Comment by Josverl** [comment]
I have published the `micropythin-esp8266-stubs`  to PyPi  
https://pypi.org/project/micropython-esp8266-stubs/

if neovim understands python stubs, it should work, or work for the best part.

- I have tested extensively with **PyLance** and **PyRight** for linting , hinting and code completion.
- I have not tested NeoVim , 
- but [it is said that is can work with PyRight](https://ramezanpour.net/post/2021/04/24/My-ultimate-Neovim-configuration-for-Python-development),
- So assuming correct integration and configuration, NeoVim + coc-Pyright should be able to use **PyRight** as well.

id start with just installing the stubs 
- either in your python environment 
  `pip install -I micropython-<port>-stubs`
  
- or in a typings folder for pyright to use
  `pip install -I micropython-<port>-stubs --target ./typings` 


please do let me know if it works, and if any special configuration is needed , as others may want to use the same.


For Micopy-cli you should really ask Braden in the discussions / isses  in that repro. I do not think that pasting the question elsewhere will get you that answer any sooner.
